### ISSUE TITLE
Window 10 path issue

### ISSUE THREAD

**Issue by cs1193** [vishaltelangre/music-dl#4] opened 2017-06-19 15:13 UTC
@vishaltelangre I installed `music-dl` in Windows 10,  it is attempting read data of package.json and it showed path issues.

    C:\Users\****\AppData\Roaming\npm\node_modules\music-dl\index.js:7
    const {name, version} = require('./package.json');
          ^
    
    SyntaxError: Unexpected token {
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Function.Module.runMain (module.js:441:10)
        at startup (node.js:139:18)
        at node.js:974:3

**Comment by vishaltelangre** [comment] 2017-06-19 15:24
@cs1193 Thanks for reporting.

I do not have a Windows machine, so really can't reproduce and fix it. 

The above error is saying that it is not able to understand the ES6[ destructuring assignment](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring) syntax. I suspect that the Node.js version you're using needs an upgrade or something.

Please try installing/upgrading Node.js version to 6.3 or latest and npm version to 5.0 or latest.

Another issue could be that the Windows may not be able to understand the UNIX-style paths.

**Comment by vishaltelangre** [comment] 2017-06-19 15:28
@cs1193 Looks like the issue is with the older versions of Node.js. Check this thread - https://stackoverflow.com/a/17379714/1052356.

Please let me know if it works after upgrading the Node.js to v6.x or latest.

**Comment by vishaltelangre** [comment] 2017-06-20 05:30
Closing this. We can reopen it if you face it even after upgrading the Node.js version.

**Closed as completed by vishaltelangre** 2017-06-20 05:30 UTC
Labels: windows
